### ISSUE TITLE
Global inheritance of inputs and outputs to reuse them in multiple cycle-tasks

### ISSUE THREAD

**Issue by agoscinski** [C2SM/ETHIOPIA#26]
### Objective

To conveniently use tasks multiple times in the cycles without respecifying all the inputs in each cycle-task. We need some option to inherit inputs from a base definition (similar idea of the root task that all tasks inherit from). This is also later important for the namelist as we want to specify it only once. 

### Proposition

The inputs that do not change over the workflow can then be put into the task

```yml
tasks:
- icon_task:
    plugin: icon
    code: icon_code
    computer: localhost
    # global inputs that are inherited by each cycle task
    # and can be overwritten in the cycle task
    inputs:
    - grid:
        port_name: icon_grid_simple.nc
    - icon_restart:
        lag: -2PM
        port_name: restart_file   # needs still implementation on aiida-icon side
    outputs:
    - icon_restart:
        port_name: latest_restart_file
```

The inheritance from tasks to cycle-task would be a union, since otherwise you need to specify all inputs again if you only want to change one. One problem that follows from this is how to overwrite inputs. An existing input is only overwritten when it is respecified in the cycle-task. What is a bit weird is to overwrite the port usage in the example above, one has to do
```yml
cycles:
- icon_cycle:
    period: 3PM
    tasks:
    - icon_task:
        - custom_grid:
            port_name: icon_grid_simple.nc
```
So this overwrites the usage of `grid` in this icon_task instance. On the other hand to overwrite an option one would need to respecify the data node name 
```yml
cycles:
- icon_cycle:
    period: 3PM
    tasks:
    - icon_task:
        - grid:
            lag: -2PM
```
We had also the suggestion to use the port_names as key name, but this does not work for the data section which result in inconsitencies somewhere else. If one would choose this way we would have such files
```yml
cycles:
- icon_cycle:
    period: 3PM
    tasks:
    - icon_task:
        - icon_grid_simple.nc
            data: grid
...
data:
- grid:
    type: file
    src: $PWD/tests/files/simple_icon_run/inputs/icon_grid_simple.nc
```

I don't have an idea that resolves this nicely. Personally I am right now tending to the last option, but no strong tendency.
