### ISSUE TITLE
workflow input data

### ISSUE THREAD

**Issue by leclairm** [C2SM/ETHIOPIA#28]
Currently we distinguish between data available at the start and sockets in very indirect way, by testing if it belongs to the unrolled tasks outputs. Such data should not get unrolled and get an `unrolled_date` attribute. We need a class for it, like `WorkflowInputData` or `AbsData` and the corresponding list in the `Workflow` object. 

Potentially, we could also make this distinction even clearer, directly in the yaml file with sub sections of the `data` section, like
```yaml
data:
    workflow input:
      - abs_data_1
      - abs_data_2
    sockets:
      - icon_output_stream_1
      - icon_output_stream_2
```
To be discussed

In the long run, having workflow input and output data could even help integrating it as an element in an AiiDA workflow.

**Comment by agoscinski** [comment]
Because you also suggested that we could have outputs, I thought about `inputs`, `intermediates`, `outputs`, or to shorter `in`, `inter`, `out` that also distinguishes it a bit more from the `inputs` and  `outputs` in the graph/cycle-tasks.
```yml
data:
    in:
      - abs_data_1
    inter:
      - icon_output_stream_2
    out:
      - density_file
```


It is also not a great naming, not intuitive, but I don't have a better idea. One could also make this keys of the data
```yml
data:
    - abs_data_1
        available_on_init: True
    - icon_output_stream_2
    - density_file
        expose_as_output: True
```
but it does not enforce a nice sorting. Maybe we just highlight the inputs and outputs and
```yml
data:
    inputs:
      - abs_data_1
    - icon_output_stream_2
    outputs:
      - density_file
```
Also not great.

**Comment by leclairm** [comment]
I think the last suggestion is not a valid yaml file.

I thought about `available` vs `generated`. it has the advantage of being rather clear but diverges from the notion of input and output at the workflow level (workflow output is necessarily generated)

**Comment by GeigerJ2** [comment]
Just chiming in here, as I think it's a suitable place for the discussion, rather than opening another issue:
For actually running an ICON simulation through `aiida-icon` with our tool here, if given data (files or folders) are located on a remote machine, we should create AiiDA `orm.RemoteData` nodes. This is also given in the `IconCalculation` spec, e.g., [see here](https://github.com/aiida-icon/aiida-icon/blob/bf372d1ed9884398afc96094b54a52cbf0353930/src/aiida_icon/calculations.py#L30-L34):
```python
        spec.input(
            "dynamics_grid_file",
            valid_type=orm.RemoteData,
        )
        spec.input("ecrad_data", valid_type=orm.RemoteData)
```

I assume this will be the case for most of the files that are available at the beginning of the workflow (apart from the namelists). However, to generate the `orm.RemoteData` instances, one has to specify the remote computer on which these files are located. So I'm wondering if we should add another `type` to the `data` section, e.g., `remote`  (note that AiiDA's `orm.RemoteData` doesn't differentiate between files and folders), as well as a `computer` input would be required (again, important to note the difference between CW tools usually running _on the remote_, while AiiDA usually _runs locally_).

One could specify the remote computer, e.g., Todi, in the `root` task, which then gets chosen as the default. Open to any other proposals, though.

**Comment by leclairm** [comment]
This is also true for the task themselves, they also need to be told, they have to run on the remote machine and this is the same machine for all of them, so this should probably be a root property of the workflow, like:
```yaml
start_date: 2026-01-01T00:00
end_date: 2027-01-01T00:00
host: santis.cscs.ch
- cycles:
[...]
```
